accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"  # Namespace for this app

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("activate/<uidb64>/<token>/", views.ActivateView.as_view(), name="activate"),
    path(
        "change-password/",
        views.CustomPasswordChangeView.as_view(),
        name="change_password",
    ),
    # Default Django names for password reset URLs
    path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path("password_reset/done/", views.password_reset_done, name="password_reset_done"),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("reset/done/", views.password_reset_complete, name="password_reset_complete"),
    path(
        "email-confirmation/",
        views.EmailConfirmationPageView.as_view(),
        name="email_confirmation_page",
    ),
    path(
        "resend-activation-email/",
        views.ResendActivationEmailView.as_view(),
        name="resend_activation_email",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
]

blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    CommentCreateView,
    ReplyCreateView,
)

app_name = "blog"

urlpatterns = [
    path("", PostListView.as_view(), name="post-list"),
    path("create/", PostCreateView.as_view(), name="post-create"),
    path("<slug:slug>/", PostDetailView.as_view(), name="post-detail"),
    path("<slug:slug>/edit/", PostUpdateView.as_view(), name="post-edit"),
    path("<slug:slug>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("<slug:slug>/comment/", CommentCreateView.as_view(), name="comment-create"),
    path(
        "<slug:slug>/comment/<int:comment_id>/reply/",
        ReplyCreateView.as_view(),
        name="comment-reply",
    ),
]

thomasd9e/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path(settings.SECRET_PATH + "/admin/", admin.site.urls),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("blog/", include("blog.urls", namespace="blog")),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from ckeditor.fields import RichTextField


class Post(models.Model):
    POST_STATUSES = [
        ("draft", "Draft"),
        ("published", "Published"),
        ("archived", "Archived"),
    ]

    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    content = RichTextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="posts",
    )
    post_status = models.CharField(
        max_length=10, choices=POST_STATUSES, default="draft"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post-detail", kwargs={"slug": self.slug})


class Comment(models.Model):
    content = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="comments",
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    parent_comment = models.ForeignKey(
        "self", on_delete=models.SET_NULL, null=True, blank=True, related_name="replies"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.author} on {self.post.title}"

blog/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "post_status"]
        widgets = {
            "slug": forms.TextInput(attrs={"readonly": "readonly"}),
        }

    # Using CKEditor for the content field
    content = forms.CharField(widget=CKEditorWidget())


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Comment
from .forms import CommentForm, PostForm  # You'll need to create these forms


class PostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "posts"
    ordering = ["-created_at"]
    paginate_by = 10


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = Comment.objects.filter(post=self.object)
        context["form"] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = self.get_object()
            comment.save()
            return redirect("blog:post-detail", slug=self.get_object().slug)
        return self.get(request, *args, **kwargs)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog/post_form.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "blog/post_form.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "blog/post_confirm_delete.html"
    success_url = reverse_lazy("post-list")

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "blog/comment_form.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, slug=self.kwargs["slug"])
        return super().form_valid(form)


class ReplyCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = "blog/reply_form.html"
    fields = ["content"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, slug=self.kwargs["slug"])
        form.instance.parent_comment = get_object_or_404(
            Comment, id=self.kwargs["comment_id"]
        )
        return super().form_valid(form)

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'website/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static '/blog/styles.css' %}">
    <title>Deli Digest</title>
</head>
<body>
    <header class="site-header">
        <nav class="main-nav">
            <div class="nav-left">
                <div class="site-brand">
                    <a href="{% url 'blog:post-list' %}" class="nav-link">
                        <i class="material-icons">home</i>
                        <span class="link-text">Deli Digest</span>
                    </a>
                </div>
            </div>
                
            <div class="nav-center">
                <div class="create-post">
                    <a href="{% url 'blog:post-create' %}" class="nav-link">
                        <i class="material-icons">add_circle</i>
                        <span class="link-text">Create a post</span>
                    </a>
                </div>
            </div>
                
            <div class="nav-right">
                <div class="user-actions">
                    {% if user.is_authenticated %}
                    <!-- If user is logged in -->
                    <a href="{% url 'accounts:profile' %}" class="nav-link">
                        <i class="material-icons">person</i>
                        <span class="link-text">Profile</span>
                    </a>                
                    {% else %}
                    <!-- If user is not logged in -->
                    <a href="{% url 'accounts:login' %}" class="nav-link">
                        <i class="material-icons">login</i>
                        <span class="link-text">Login</span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>
    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="site-footer">
        <p>© 2023 Your Blog Name</p>
    </footer>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>Add Comment</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>Are you sure you want to delete this post?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
    </form>
    <a href="{% url 'blog:post-detail' object.slug %}">Cancel</a>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <p>By {{ object.author }} on {{ object.created_at }}</p>
    <div>{{ object.content|safe }}</div>

    <h2>Comments</h2>
    {% for comment in comments %}
        <div>
            <strong>{{ comment.author }}</strong> said:
            <p>{{ comment.content }}</p>
        </div>
    {% endfor %}

    <h2>Add a Comment</h2>
    <form method="post" action="{% url 'blog:post-detail' object.slug %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>{% if object %}Edit Post{% else %}New Post{% endif %}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="main-container">
        <div class="main-left">
        <h2>Recent Posts</h2>
        {% for post in posts %}
        <a href="{% url 'blog:post-detail' post.slug %}" class="card-link">
            <div class="card">
                <p class="card-title">{{ post.title }}</p>
                <p class="card-byline">By {{ post.author }} on {{ post.created_at }}</p>
            </div>
        </a>
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        </div>
        <div class="main-right">
            <h2>League Standings</h2>
            <table border="1">
                <thead>
                    <tr>
                        <th>Team</th>
                        <th>W</th>
                        <th>L</th>
                        <th>T</th>
                        <th>Pts</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Titans</td>
                        <td>7</td>
                        <td>2</td>
                        <td>1</td>
                        <td>2150</td>
                    </tr>
                    <tr>
                        <td>Falcons</td>
                        <td>7</td>
                        <td>2</td>
                        <td>1</td>
                        <td>2180</td>
                    </tr>
                    <tr>
                        <td>Dragons</td>
                        <td>6</td>
                        <td>3</td>
                        <td>1</td>
                        <td>2100</td>
                    </tr>
                    <tr>
                        <td>Lions</td>
                        <td>6</td>
                        <td>3</td>
                        <td>1</td>
                        <td>2070</td>
                    </tr>
                    <tr>
                        <td>Eagles</td>
                        <td>6</td>
                        <td>3</td>
                        <td>1</td>
                        <td>2130</td>
                    </tr>
                    <tr>
                        <td>Warriors</td>
                        <td>5</td>
                        <td>4</td>
                        <td>1</td>
                        <td>2050</td>
                    </tr>
                    <tr>
                        <td>Wolves</td>
                        <td>5</td>
                        <td>4</td>
                        <td>1</td>
                        <td>2020</td>
                    </tr>
                    <tr>
                        <td>Sharks</td>
                        <td>5</td>
                        <td>4</td>
                        <td>1</td>
                        <td>2040</td>
                    </tr>
                    <tr>
                        <td>Phoenix</td>
                        <td>4</td>
                        <td>5</td>
                        <td>1</td>
                        <td>2000</td>
                    </tr>
                    <tr>
                        <td>Hawks</td>
                        <td>4</td>
                        <td>5</td>
                        <td>1</td>
                        <td>1980</td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}

blog/templates/blog/reply_form.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>Reply to Comment</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}